name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: actions/checkout@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"


# Code pushed to GitHub
# GitHub Actions starts workflow "Checks"
# Creates Ubuntu machine
# Runs job: Test and lint
# Step: Login to Docker Hub
# Later steps can build/run containers